<?php

define('ELAINE_RESTAURANT_VERSION', '1.0');
define('ELAINE_RESTAURANT_ABS_PATH', dirname(__FILE__));
define('ELAINE_RESTAURANT_REL_PATH', dirname(plugin_basename(__FILE__ )));
define('ELAINE_RESTAURANT_URL_PATH', plugin_dir_url( __FILE__ ));
define('ELAINE_RESTAURANT_ASSETS_PATH', ELAINE_RESTAURANT_ABS_PATH.'/assets');
define('ELAINE_RESTAURANT_ASSETS_URL_PATH', ELAINE_RESTAURANT_URL_PATH.'assets');
define('ELAINE_RESTAURANT_CPT_PATH', ELAINE_RESTAURANT_ABS_PATH.'/post-types');
define('ELAINE_RESTAURANT_SHORTCODES_PATH', ELAINE_RESTAURANT_ABS_PATH.'/modules/shortcodes');